# Generated by Django 2.2.24 on 2021-12-02 17:32

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('verified_user', models.BooleanField(default=True, verbose_name='Verificado')),
                ('destino', models.CharField(max_length=200, verbose_name='Destinos:')),
                ('dataInicial', models.CharField(max_length=8, verbose_name='Ida:')),
                ('dataFinal', models.CharField(max_length=8, verbose_name='Volta:')),
                ('contratante', models.CharField(max_length=200, verbose_name='Contratante:')),
                ('valorPgt', models.IntegerField(verbose_name='Total a pagar:')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ('valorPgt',),
            },
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('verified_user', models.BooleanField(default=True, verbose_name='Verificado')),
                ('nomeDestino', models.CharField(max_length=200, verbose_name='Nome')),
                ('precoPorPessoa', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True)),
                ('imagem', stdimage.models.StdImageField(upload_to='produtos', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'destinos',
                'ordering': ('nomeDestino',),
            },
        ),
    ]
